-- ============================================================
-- Upload Static Files via APEX Import Mechanism
-- ============================================================
-- This script uses the same import mechanism that APEX's own
-- export/import uses, bypassing the "Runtime API Usage"
-- self-modification block in APEX 24.2.
--
-- It re-imports the exported static file SQL from apex/f102/.
-- To update CSS/JS: edit files in App Builder, run 'make export',
-- then run this script (or 'make upload') to push changes.
--
-- Alternatively, edit the exported SQL files directly and run
-- this script to push them into the app.
-- ============================================================

set define off verify off feedback off
set serveroutput on
whenever sqlerror exit sql.sqlcode rollback

prompt
prompt ========================================
prompt   Uploading Static Files (Import Mode)
prompt ========================================
prompt

-- Step 1: Establish import context (same as APEX export uses)
-- This permits wwv_flow_imp_shared calls to bypass Runtime API Usage checks.
begin
wwv_flow_imp.import_begin (
 p_version_yyyy_mm_dd=>'2024.11.30'
,p_release=>'24.2.13'
,p_default_workspace_id=>13027568242155993
,p_default_application_id=>102
,p_default_id_offset=>0
,p_default_owner=>'USCIS_APP'
);
end;
/

-- Step 2: Remove existing non-icon static files to avoid duplicate ID conflicts.
-- Within the import context, wwv_flow_imp calls are permitted.
prompt Removing existing static files...
declare
    l_count pls_integer := 0;
begin
    for r in (
        select application_file_id, file_name
        from apex_application_static_files
        where application_id = 102
        and file_name not like 'icons/%'
    ) loop
        begin
            wwv_flow_imp.remove_app_static_file(
                p_id      => r.application_file_id,
                p_flow_id => 102
            );
            l_count := l_count + 1;
        exception
            when others then
                dbms_output.put_line('Warning: could not remove '
                    || r.file_name || ': ' || sqlerrm);
        end;
    end loop;
    dbms_output.put_line('Removed ' || l_count || ' existing static file(s).');
end;
/

-- Step 3: Re-import static files from APEX export format.
-- These files use wwv_flow_imp.component_begin / wwv_flow_imp_shared.create_app_static_file
-- which is the standard format generated by 'apex export -split'.
prompt Importing app-styles.css...
@@../apex/f102/application/shared_components/files/app_styles_css.sql

prompt Importing css/app-styles.css...
@@../apex/f102/application/shared_components/files/css_app_styles_css.sql

prompt Importing app-scripts.js...
@@../apex/f102/application/shared_components/files/app_scripts_js.sql

prompt Importing app-scripts.min.js...
@@../apex/f102/application/shared_components/files/app_scripts_min_js.sql

prompt Importing js/app-scripts.js...
@@../apex/f102/application/shared_components/files/js_app_scripts_js.sql

prompt Importing js/page-0006-import-export.js...
@@../apex/f102/application/shared_components/files/js_page_0006_import_export_js.sql

-- Step 4: Finalize import context and commit
begin
wwv_flow_imp.import_end(p_auto_install_sup_obj => false);
commit;
end;
/

prompt
prompt Static files uploaded successfully!
prompt Clear browser cache and refresh your APEX application.
prompt
